# Generated by Django 4.1.4 on 2022-12-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categorydb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(blank=True, max_length=100, null=True)),
                ('DISCRIPTION', models.CharField(blank=True, max_length=100, null=True)),
                ('IMAGE', models.ImageField(upload_to='profile')),
            ],
        ),
        migrations.AlterField(
            model_name='adminreg',
            name='MOBILE',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
